name: Docker Image CI

on:
  push:
    branches: [ "**" ] # Triggers the workflow on push events to all branches
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: meysam57 # Your Docker Hub username
        password: ${{ secrets.DOCKERHUB_TOKEN }} # Your Docker Hub token stored as a secret

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: meysam57/networkinfrastructureweb:latest # Replace with your Docker Hub username and desired image name/tag
